### ISSUE TITLE
Wake-on-LAN

### ISSUE THREAD

**Issue by jwnremt** [bitfocus/companion-module-generic-wakeonlan#1]
I would like a module that sends Wake-on-LAN magic packets to turn on another device (in this case my lightboard but I think others could find it useful for any hardware that allows for remote startup/WOL) on the network. 

A status indicator of the device might be nice too. (Maybe just have us select the Mac Address & the IP address so the module can ping the device to see if a response is returned, It doesn't need to be that fancy)

https://www.codeproject.com/Articles/11469/Wake-On-LAN-WOL

**Comment by josephdadams** [comment]
Here’s a library that will make creating this module pretty easy: https://github.com/gigafied/wakeonlan

It’s MIT license.

**Comment by Jibun-no-Kage** [comment]
This is appears to be broken now as of this date, 08/26/2024 with companion 3.3 (current)  installed on Windows 11 Pro (current).  I can WOL a system, which supports WOL power on, from Linux, from my phone, from Windows 11 Pro, via small app for Windows.  But when I try to use the module with companion... nothing.  Which seems odd given the dedicated application on Windows 11 Pro works.  So must be internal module issue or library issue.
